# Generated by Django 3.0.4 on 2023-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=60)),
                ('password2', models.CharField(max_length=60)),
            ],
        ),
    ]
