# Generated by Django 3.0.4 on 2021-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('dec', models.TextField()),
            ],
        ),
    ]
