# Generated by Django 3.0.4 on 2022-05-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('job_dec', models.TextField()),
                ('expo', models.IntegerField()),
            ],
        ),
    ]
